---
apiVersion: v1
kind: Service
metadata:
  name: neighborly
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: neighborly
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborly
  template:
    metadata:
      labels:
        app: neighborly
    spec:
      containers:
      - name: neighborly
        image: ndneigh.azurecr.io/neighborly-front:latest
        ports:
        - containerPort: 5000
          hostPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: azctsecret2
